# Something for the `notes` function to count. See example 02 for the resource
# itself.

[resource]
name = "note"
scope = "global"

[permissions]
list   = "public"
read   = "public"
create = "public"
update = "public"
delete = "public"

[fields.title]
type     = "string"
required = true

[fields.body]
type = "text"
