//! Building Rust functions.
//!
//! A single `.rs` file is wrapped in a generated cdylib crate — the file becomes
//! its `lib.rs` verbatim — and handed to cargo. A directory is the author's own
//! crate: it is run as written and the library it produces is copied out.

use std::io::Read;
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};

use anyhow::{bail, Context, Result};

use super::source::{Language, Source};
use super::Options;

/// Crates every generated function crate depends on. `apiplant-function` is
/// resolved separately — see [`function_crate`].
const DEPENDENCIES: &str = r#"abi_stable = "0.11"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
schemars = "0.8"
"#;

/// Build profiles for the generated crates.
///
/// A function library is a *deployment artifact* — it gets copied next to its
/// source and shipped — so cargo's defaults are the wrong trade-off here. Each
/// cdylib statically links its own copy of `std`, `serde_json` and `schemars`
/// (that independence is exactly what makes the ABI stable), and on top of that
/// cargo emits full DWARF in `dev` and leaves the symbol table in `release`.
/// The debug info alone accounted for ~94% of a `dev` library: a one-page
/// function came to 18 MB, of which 1.5 MB was actual code.
///
/// So:
///
/// * `dev` drops DWARF but keeps the symbol table, so function names still show
///   up when something crashes — 18 MB → 2.4 MB.
/// * `release` strips fully and adds fat LTO with a single codegen unit, which
///   lets the linker discard the parts of `std`/`serde_json`/`schemars` the
///   function never reaches — 1.2 MB → ~600 KB, and faster code as a bonus.
///
/// Deliberately *not* set: `opt-level = "z"` (a further ~100 KB, but these are
/// per-request handlers, so speed wins) and `panic = "abort"` (another ~80 KB,
/// but it would turn a panic in one function into an abort of the whole server).
const PROFILES: &str = r#"[profile.dev]
strip = "debuginfo"

[profile.release]
strip = "symbols"
lto = "fat"
codegen-units = 1

"#;
/// Where the generated crates get `apiplant-function` from.
pub(super) enum FunctionCrate {
    /// A directory on this machine, depended on by path.
    Local(PathBuf),
    /// A version on crates.io, for a binary with no checkout to point at.
    Published(&'static str),
}

/// Resolve the `apiplant-function` crate the generated crates depend on.
///
/// Three sources, in order: `APIPLANT_FUNCTION_CRATE`, so a released binary can
/// be pointed at a checkout; the path this binary was compiled from, which is
/// what makes `cargo run -p apiplant -- build …` work in-tree; and finally
/// crates.io at this binary's own version — the workspace versions every crate
/// in lockstep, so `apiplant` 0.3.0 goes with `apiplant-function` 0.3.0.
pub(super) fn function_crate() -> Result<FunctionCrate> {
    if let Some(configured) = std::env::var_os("APIPLANT_FUNCTION_CRATE") {
        let path = PathBuf::from(configured);
        if !path.join("Cargo.toml").is_file() {
            bail!(
                "APIPLANT_FUNCTION_CRATE points at {}, which has no Cargo.toml",
                path.display()
            );
        }
        return Ok(FunctionCrate::Local(path));
    }

    let compiled_from = Path::new(env!("CARGO_MANIFEST_DIR")).join("../apiplant-function");
    if compiled_from.join("Cargo.toml").is_file() {
        return Ok(FunctionCrate::Local(compiled_from));
    }

    Ok(FunctionCrate::Published(env!("CARGO_PKG_VERSION")))
}

/// The `Cargo.toml` for one generated crate.
///
/// The empty `[workspace]` table matters: without it cargo walks up the
/// directory tree and tries to enrol the scaffold in whatever workspace happens
/// to contain the app directory. It also means the profiles have to be spelled
/// out here — a detached crate inherits nothing from apiplant's own workspace.
pub(super) fn manifest(crate_name: &str, function_crate: &FunctionCrate) -> String {
    let function_crate = match function_crate {
        FunctionCrate::Local(path) => format!("{{ path = {path:?} }}"),
        FunctionCrate::Published(version) => format!("{version:?}"),
    };
    format!(
        "# Generated by `apiplant build` — edits are overwritten.\n\
         [package]\n\
         name = \"{crate_name}\"\n\
         version = \"0.0.0\"\n\
         edition = \"2021\"\n\
         publish = false\n\
         \n\
         [lib]\n\
         name = \"{crate_name}\"\n\
         path = \"src/lib.rs\"\n\
         crate-type = [\"cdylib\"]\n\
         \n\
         [dependencies]\n\
         apiplant-function = {function_crate}\n\
         {DEPENDENCIES}\n\
         {PROFILES}\n\
         [workspace]\n"
    )
}

/// Scaffold and compile one Rust source file.
pub(super) fn compile_rust(
    source: &Source,
    build_dir: &Path,
    target_dir: &Path,
    function_crate: &FunctionCrate,
    options: Options,
) -> Result<()> {
    let crate_dir = build_dir.join(&source.crate_name);
    let src_dir = crate_dir.join("src");
    std::fs::create_dir_all(&src_dir).with_context(|| format!("creating {}", src_dir.display()))?;

    // The function's own file becomes the crate's lib.rs verbatim.
    std::fs::copy(&source.path, src_dir.join("lib.rs"))
        .with_context(|| format!("copying {}", source.path.display()))?;
    std::fs::write(
        crate_dir.join("Cargo.toml"),
        manifest(&source.crate_name, function_crate),
    )
    .with_context(|| format!("writing {}/Cargo.toml", crate_dir.display()))?;

    let mut cargo = Command::new(Language::Rust.command());
    cargo
        .arg("build")
        .arg("--manifest-path")
        .arg(crate_dir.join("Cargo.toml"))
        .arg("--target-dir")
        .arg(target_dir);
    if options.release {
        cargo.arg("--release");
    }

    let status = cargo.status().with_context(|| {
        "failed to run `cargo` — apiplant compiles function sources with it, \
         so it must be installed and on PATH"
    })?;
    if !status.success() {
        bail!(
            "compiling {} failed; see cargo's output above",
            source.path.display()
        );
    }
    Ok(())
}

/// Build a Rust *directory* — the author's own crate — into `library`.
///
/// Nothing is scaffolded here: the crate's `Cargo.toml` is run as written, so its
/// dependencies, modules and profiles are entirely the author's. The one thing
/// apiplant can't assume is what the crate *named* its cdylib, so cargo is asked
/// for structured output (`--message-format=json-render-diagnostics`, which still
/// prints human diagnostics to stderr) and the produced library is read back from
/// it and copied to `functions/lib<dir>.so`.
pub(super) fn compile_rust_dir(
    source: &Source,
    target_dir: &Path,
    library: &Path,
    options: Options,
) -> Result<()> {
    let manifest_path = source.path.join("Cargo.toml");
    let mut cargo = Command::new(Language::Rust.command());
    cargo
        .arg("build")
        .arg("--manifest-path")
        .arg(&manifest_path)
        .arg("--target-dir")
        .arg(target_dir)
        .arg("--message-format=json-render-diagnostics")
        .stdout(Stdio::piped())
        .stderr(Stdio::inherit());
    if options.release {
        cargo.arg("--release");
    }

    let mut child = cargo.spawn().with_context(|| {
        "failed to run `cargo` — apiplant compiles function sources with it, \
         so it must be installed and on PATH"
    })?;
    let mut json = String::new();
    child
        .stdout
        .take()
        .expect("stdout was piped")
        .read_to_string(&mut json)
        .context("reading cargo output")?;
    let status = child.wait().context("waiting for cargo")?;
    if !status.success() {
        bail!(
            "compiling {} failed; see cargo's output above",
            source.path.display()
        );
    }

    let produced = cdylib_from_cargo_output(&json).with_context(|| {
        format!(
            "cargo built {} but produced no cdylib — is `crate-type = [\"cdylib\"]` set?",
            source.path.display()
        )
    })?;
    std::fs::copy(&produced, library)
        .with_context(|| format!("copying {} to {}", produced.display(), library.display()))?;
    Ok(())
}

/// The cdylib a `cargo build --message-format=json` run produced.
///
/// Cargo emits one JSON object per line; a `compiler-artifact` message lists the
/// files a crate produced under `filenames`. The crate at the manifest path is
/// compiled last, so the last cdylib-shaped filename is the library we want.
pub(super) fn cdylib_from_cargo_output(json: &str) -> Option<PathBuf> {
    let mut cdylib = None;
    for line in json.lines() {
        let Ok(message) = serde_json::from_str::<serde_json::Value>(line) else {
            continue;
        };
        if message.get("reason").and_then(|r| r.as_str()) != Some("compiler-artifact") {
            continue;
        }
        let Some(filenames) = message.get("filenames").and_then(|f| f.as_array()) else {
            continue;
        };
        for filename in filenames {
            let Some(path) = filename.as_str() else {
                continue;
            };
            if is_dynamic_library(Path::new(path)) {
                cdylib = Some(PathBuf::from(path));
            }
        }
    }
    cdylib
}

/// Whether a filename looks like the dynamic library for this platform.
fn is_dynamic_library(path: &Path) -> bool {
    let ext = path.extension().and_then(|e| e.to_str());
    if cfg!(target_os = "windows") {
        ext == Some("dll")
    } else if cfg!(target_os = "macos") {
        ext == Some("dylib")
    } else {
        ext == Some("so")
    }
}
