//! Building TypeScript functions.
//!
//! The odd one out, in two ways. Every other language here shells out to a
//! toolchain the author installed; TypeScript is transpiled inside `apiplant
//! build`, so `functions/greet.ts` needs nothing on `PATH` — no node, no deno,
//! no bun. And every other language produces a shared library the host
//! `dlopen`s; this one produces `functions/greet.js`, which the host runs in a
//! V8 isolate instead (see `apiplant_js`).
//!
//! What "compiling" means here is stripping the types. There is no bundler, so a
//! function is one self-contained file — a module that `import`s is rejected at
//! build time with that explanation rather than at boot with a missing-module
//! error.

use std::path::Path;

use anyhow::{Context, Result};

use super::source::Source;

/// The declarations file written beside an app's TypeScript functions.
const DECLARATIONS: &str = "apiplant.d.ts";

/// Transpile a `.ts` source into the `.js` beside it.
pub(super) fn compile_typescript(source: &Source, library: &Path) -> Result<()> {
    let text = std::fs::read_to_string(&source.path)
        .with_context(|| format!("reading {}", source.path.display()))?;

    let js = apiplant_js::transpile::to_js(&source.crate_name, &text)
        .map_err(|e| anyhow::anyhow!("{}:\n{e}", source.path.display()))?;

    // A header, because the output sits in `functions/` beside its source and
    // the first question anyone editing it will have is where it came from.
    let output = format!(
        "// Generated by `apiplant build` from {}. Do not edit; edit the .ts.\n{js}",
        source
            .path
            .file_name()
            .unwrap_or_default()
            .to_string_lossy()
    );

    std::fs::write(library, output).with_context(|| format!("writing {}", library.display()))?;
    Ok(())
}

/// The tsconfig written beside them, so an editor reads the declarations the
/// way the runtime means them.
const TSCONFIG: &str = "tsconfig.json";

/// What that tsconfig says.
///
/// The important line is `lib`. A function runs in a V8 isolate, not a browser
/// and not Node, so `DOM` would offer an author `fetch`, `localStorage` and a
/// `console` that disagrees with the one the host provides — types for things
/// that are not there. Naming the libraries keeps the editor honest about what
/// an isolate actually has.
const TSCONFIG_SOURCE: &str = r#"{
  "//": "Written by `apiplant build` so an editor types functions the way the isolate runs them. Yours to edit.",
  "compilerOptions": {
    "target": "ES2022",
    "module": "ESNext",
    "moduleResolution": "bundler",
    "lib": ["ES2022"],
    "types": [],
    "strict": true,
    "noEmit": true,
    "allowImportingTsExtensions": true
  },
  "include": ["*.ts"]
}
"#;

/// Write `apiplant.d.ts` and a `tsconfig.json` into the app's `functions/`
/// directory.
///
/// This is what types the `apiplant` module, `ctx` and the manifest while an
/// author is writing a function, with no package to install: TypeScript picks up
/// a `.d.ts` sitting next to the source, and the declarations describe
/// `"apiplant"` as an ambient module, so the import resolves with no
/// `node_modules` and no `paths` entry.
///
/// The declarations are rewritten on every build so they track the binary doing
/// the building, and left alone when they already match — an untouched mtime
/// keeps editors from re-indexing and keeps the file out of a "what changed?"
/// diff. The tsconfig is only ever *created*: it is the author's after that.
pub(super) fn write_declarations(functions_dir: &Path) -> Result<()> {
    let path = functions_dir.join(DECLARATIONS);
    let current = apiplant_js::transpile::DECLARATIONS;
    if !std::fs::read_to_string(&path).is_ok_and(|existing| existing == current) {
        std::fs::write(&path, current).with_context(|| format!("writing {}", path.display()))?;
        tracing::info!(path = %path.display(), "wrote TypeScript declarations");
    }

    let tsconfig = functions_dir.join(TSCONFIG);
    if !tsconfig.exists() {
        std::fs::write(&tsconfig, TSCONFIG_SOURCE)
            .with_context(|| format!("writing {}", tsconfig.display()))?;
        tracing::info!(path = %tsconfig.display(), "wrote TypeScript configuration");
    }
    Ok(())
}
