//! Building TypeScript functions.
//!
//! The odd one out, because it is the only language here that does not produce a
//! shared library: `functions/greet.ts` becomes `functions/greet.js`, which the
//! host runs in a V8 isolate rather than `dlopen`ing (see `apiplant_js`).
//!
//! ## A file needs nothing; a directory is npm
//!
//! A single `.ts` file is transpiled **inside `apiplant build`** — no node, no
//! deno, no bun, nothing on `PATH`. "Compiling" it means stripping the types,
//! and since nothing bundles, it is one self-contained file that may import only
//! the [`apiplant`](apiplant_js) module.
//!
//! A **directory** is where dependencies live, and it follows the same rule
//! every other language's directory follows: it is a project in the language's
//! own native form, built by the language's own toolchain. For TypeScript that
//! means a `package.json`, your dependencies, and your bundler — apiplant runs
//! `<pm> install` and `<pm> run build`, then copies the bundle out, exactly as
//! it runs your `Cargo.toml` or your `go.mod` and copies out the library.
//!
//! So the toolchain requirement follows the layout: a file needs nothing, and a
//! directory needs the node toolchain the project itself already implies.

use std::path::{Path, PathBuf};
use std::process::Command;

use anyhow::{bail, Context, Result};
use serde_json::Value;

use super::source::Source;
use super::{run, Options};

/// The declarations file written beside an app's TypeScript functions.
const DECLARATIONS: &str = "apiplant.d.ts";

/// Transpile a `.ts` source into the `.js` beside it.
pub(super) fn compile_typescript(source: &Source, library: &Path) -> Result<()> {
    let text = std::fs::read_to_string(&source.path)
        .with_context(|| format!("reading {}", source.path.display()))?;

    let js = apiplant_js::transpile::to_js(&source.crate_name, &text)
        .map_err(|e| anyhow::anyhow!("{}:\n{e}", source.path.display()))?;

    // A header, because the output sits in `functions/` beside its source and
    // the first question anyone editing it will have is where it came from.
    let output = format!(
        "// Generated by `apiplant build` from {}. Do not edit; edit the .ts.\n{js}",
        source
            .path
            .file_name()
            .unwrap_or_default()
            .to_string_lossy()
    );

    std::fs::write(library, output).with_context(|| format!("writing {}", library.display()))?;
    Ok(())
}

/// The tsconfig written beside them, so an editor reads the declarations the
/// way the runtime means them.
const TSCONFIG: &str = "tsconfig.json";

/// What that tsconfig says.
///
/// The important line is `lib`. A function runs in a V8 isolate, not a browser
/// and not Node, so `DOM` would offer an author `fetch`, `localStorage` and a
/// `console` that disagrees with the one the host provides — types for things
/// that are not there. Naming the libraries keeps the editor honest about what
/// an isolate actually has.
const TSCONFIG_SOURCE: &str = r#"{
  "//": "Written by `apiplant build` so an editor types functions the way the isolate runs them. Yours to edit.",
  "compilerOptions": {
    "target": "ES2022",
    "module": "ESNext",
    "moduleResolution": "bundler",
    "lib": ["ES2022"],
    "types": [],
    "strict": true,
    "noEmit": true,
    "allowImportingTsExtensions": true
  },
  "include": ["*.ts"]
}
"#;

/// Write `apiplant.d.ts` and a `tsconfig.json` into the app's `functions/`
/// directory.
///
/// This is what types the `apiplant` module, `ctx` and the manifest while an
/// author is writing a function, with no package to install: TypeScript picks up
/// a `.d.ts` sitting next to the source, and the declarations describe
/// `"apiplant"` as an ambient module, so the import resolves with no
/// `node_modules` and no `paths` entry.
///
/// The declarations are rewritten on every build so they track the binary doing
/// the building, and left alone when they already match — an untouched mtime
/// keeps editors from re-indexing and keeps the file out of a "what changed?"
/// diff. The tsconfig is only ever *created*: it is the author's after that.
pub(super) fn write_declarations(functions_dir: &Path) -> Result<()> {
    let path = functions_dir.join(DECLARATIONS);
    let current = apiplant_js::transpile::DECLARATIONS;
    if !std::fs::read_to_string(&path).is_ok_and(|existing| existing == current) {
        std::fs::write(&path, current).with_context(|| format!("writing {}", path.display()))?;
        tracing::info!(path = %path.display(), "wrote TypeScript declarations");
    }

    let tsconfig = functions_dir.join(TSCONFIG);
    if !tsconfig.exists() {
        std::fs::write(&tsconfig, TSCONFIG_SOURCE)
            .with_context(|| format!("writing {}", tsconfig.display()))?;
        tracing::info!(path = %tsconfig.display(), "wrote TypeScript configuration");
    }
    Ok(())
}

// ---- directories: a package, its dependencies, and its bundler --------------

/// Build a TypeScript function *directory* — an npm project — into `library`.
///
/// The project is yours, like a Rust directory's crate or a Go directory's
/// module: apiplant does not choose your bundler, generate a config or rewrite
/// your `package.json`. It installs (once), runs your `build` script, checks
/// that what came out can actually be loaded, and copies it beside the directory
/// as `<name>.js`.
///
/// Two things the bundle must be, both checked below rather than left to fail at
/// boot: **ESM**, because the isolate loads a module, and free of imports other
/// than `apiplant`, which means marking that one external — nothing else is
/// resolvable at runtime, by design.
pub(super) fn compile_typescript_dir(
    source: &Source,
    library: &Path,
    options: Options,
) -> Result<()> {
    let manifest = read_package_json(&source.path)?;
    let manager = PackageManager::detect(&source.path);

    // Installing on every build would hit the network (or at least the store)
    // for a directory that has not changed. The lockfile is the author's to
    // update, and `node_modules` being there is what says they have.
    if !source.path.join("node_modules").is_dir() {
        tracing::info!(
            function = %source.crate_name,
            manager = manager.command(),
            "installing dependencies",
        );
        let mut install = manager.at(&source.path);
        install.arg("install");
        run(install, source)?;
    }

    if !has_build_script(&manifest) {
        bail!(
            "{} has no `build` script.\n\
             apiplant runs `{} run build` and loads what it produces, so the \
             package decides how it is bundled. For example:\n\n  \
             \"scripts\": {{ \"build\": \"esbuild src/index.ts --bundle --format=esm \
             --platform=neutral --main-fields=module,main --external:apiplant \
             --outfile=dist/{}.js\" }},\n  \
             \"module\": \"dist/{}.js\"\n\n\
             `--external:apiplant` matters: the module is provided by the host, \
             not installed.",
            source.path.join("package.json").display(),
            manager.command(),
            source.crate_name,
            source.crate_name,
        );
    }

    let mut build = manager.at(&source.path);
    build.arg("run").arg("build");
    // A bundler that reads NODE_ENV is the common case, and `--release` is the
    // only signal apiplant has about which build this is.
    if options.release {
        build.env("NODE_ENV", "production");
    }
    run(build, source)?;

    let bundle = bundle_path(&source.path, &manifest, &source.crate_name);
    if !bundle.is_file() {
        bail!(
            "`{} run build` reported success but {} was not produced.\n\
             apiplant looks for the package's `module` field, then `main`, then \
             `dist/{}.js` — point one of them at the bundle your build writes.",
            manager.command(),
            bundle.display(),
            source.crate_name,
        );
    }

    let code = std::fs::read_to_string(&bundle)
        .with_context(|| format!("reading {}", bundle.display()))?;
    apiplant_js::transpile::check_bundle(&code).map_err(|e| {
        anyhow::anyhow!(
            "{} cannot be loaded:\n{e}\n\
             Bundle to ESM with `apiplant` external, e.g. `--format=esm \
             --platform=neutral --main-fields=module,main --external:apiplant`.",
            bundle.display()
        )
    })?;

    let header = format!(
        "// Bundled by `{} run build` from {}/. Do not edit; edit the sources.\n",
        manager.command(),
        source.crate_name,
    );
    std::fs::write(library, format!("{header}{code}"))
        .with_context(|| format!("writing {}", library.display()))?;
    Ok(())
}

/// The `package.json` a TypeScript directory is built from.
fn read_package_json(dir: &Path) -> Result<Value> {
    let path = dir.join("package.json");
    let text =
        std::fs::read_to_string(&path).with_context(|| format!("reading {}", path.display()))?;
    serde_json::from_str(&text).with_context(|| format!("{} is not valid JSON", path.display()))
}

fn has_build_script(manifest: &Value) -> bool {
    manifest
        .get("scripts")
        .and_then(|scripts| scripts.get("build"))
        .and_then(Value::as_str)
        .is_some_and(|script| !script.trim().is_empty())
}

/// Where the bundle lands: what the package says, or the conventional path.
///
/// `module` before `main` because the isolate loads ESM, and a package that
/// distinguishes the two puts the ESM build in `module`.
pub(super) fn bundle_path(dir: &Path, manifest: &Value, name: &str) -> PathBuf {
    let declared = ["module", "main"]
        .iter()
        .find_map(|key| manifest.get(*key).and_then(Value::as_str))
        .filter(|value| !value.trim().is_empty());
    match declared {
        Some(relative) => dir.join(relative),
        None => dir.join("dist").join(format!("{name}.js")),
    }
}

/// Which package manager runs the project.
///
/// Read from the lockfile the project already has, because that is the one
/// answer nobody has to configure and the one that cannot be wrong — a project
/// with a `pnpm-lock.yaml` is a pnpm project. `NODE_PACKAGE_MANAGER` overrides
/// it, the way `CARGO`, `CC`, `ZIG` and `GO` override the others.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(super) enum PackageManager {
    Pnpm,
    Npm,
    Yarn,
    Bun,
}

impl PackageManager {
    pub(super) fn detect(dir: &Path) -> PackageManager {
        if let Ok(configured) = std::env::var("NODE_PACKAGE_MANAGER") {
            return match configured.trim() {
                "npm" => PackageManager::Npm,
                "yarn" => PackageManager::Yarn,
                "bun" => PackageManager::Bun,
                _ => PackageManager::Pnpm,
            };
        }
        if dir.join("package-lock.json").is_file() {
            return PackageManager::Npm;
        }
        if dir.join("yarn.lock").is_file() {
            return PackageManager::Yarn;
        }
        if dir.join("bun.lockb").is_file() || dir.join("bun.lock").is_file() {
            return PackageManager::Bun;
        }
        PackageManager::Pnpm
    }

    pub(super) fn command(self) -> &'static str {
        match self {
            PackageManager::Pnpm => "pnpm",
            PackageManager::Npm => "npm",
            PackageManager::Yarn => "yarn",
            PackageManager::Bun => "bun",
        }
    }

    /// A command that runs in the project directory.
    fn at(self, dir: &Path) -> Command {
        let mut command = Command::new(self.command());
        command.current_dir(dir);
        command
    }
}
